### ISSUE TITLE
シェル芸botでヘルプが出力されない

### ISSUE THREAD

**Issue by xztaityozx** [xztaityozx/owari#29]
タイトル通り。

https://twitter.com/minyoruminyon/status/1118685190019092480

こんなふうに空の結果が返ってきてしまう

**Comment by horo17** [comment]
https://twitter.com/minyoruminyon/status/1150739596021391361

ちゃんと出てるので大丈夫そう。

**Comment by xztaityozx** [comment]
https://twitter.com/minyoruminyon/status/1150742122208694272

本当だ。何にもしてないのに直りました・・・！ありがとうございます
