### ISSUE TITLE
看板、ずれてますよ

### ISSUE THREAD

**Issue by xztaityozx** [xztaityozx/owari#37]
![image](https://user-images.githubusercontent.com/15944290/67614035-66c66300-f7f0-11e9-934f-92bba2523398.png)

ほらね

**Comment by xztaityozx** [comment]
![image](https://user-images.githubusercontent.com/15944290/67614037-8067aa80-f7f0-11e9-896d-24d3830e1948.png)

これはずれてないので、前の機能追加がダメなんじゃん？

**Comment by eggplants** [comment]
持ち手がずれているのが気になっています。

```bash
(owari kan -g
echo ===
owari kan -g|sed -r '8s/(\|\|)./  \1/')|textimg -s
```

![image](https://user-images.githubusercontent.com/42153744/126811928-d49487d6-5a27-4b35-9992-a9ea51a88ede.png)

**Comment by xztaityozx** [comment]
確かに。
持ち手の位置も違和感あるので直します

**Comment by xztaityozx** [comment]
#39 で直したっす

**Comment by eggplants** [comment]
まだずれてませんか

**Comment by eggplants** [comment]
```
$ owari --version|owari kan -g -i
|￣￣￣￣￣￣￣￣￣￣￣|
|  owari version 1.11  |
|      制作・著作      |
|  ￣￣￣￣￣￣￣￣￣  |
|       Ｎ Ｈ Ｋ       |
|＿＿＿＿＿＿＿＿＿＿＿|
    ∧∧  ||     
    ( ﾟдﾟ)||     
    /    づΦ     
```

![image](https://user-images.githubusercontent.com/42153744/127260797-94963912-31cc-4ca2-b3da-b3d6f2c17a48.png)

**Comment by eggplants** [comment]
![image](https://user-images.githubusercontent.com/42153744/127261006-f6f09967-4b22-4fa2-82d2-a639e1f0dcd1.png)

**Comment by eggplants** [comment]
```
$ owari --version|owari kan -g -i|tac|sed '3s/||/　&/'|tac

|￣￣￣￣￣￣￣￣￣￣￣|
|  owari version 1.11  |
|      制作・著作      |
|  ￣￣￣￣￣￣￣￣￣  |
|       Ｎ Ｈ Ｋ       |
|＿＿＿＿＿＿＿＿＿＿＿|
    ∧∧  　||     
    ( ﾟдﾟ)||     
    /    づΦ     
```

![image](https://user-images.githubusercontent.com/42153744/127261165-2abc36c1-6150-4f5b-a659-9ab7b78f7b51.png)

**Comment by eggplants** [comment]
こなたもずれてます
```
$ owari --version|owari kan -g -i --konata

|￣￣￣￣￣￣￣￣￣￣￣|
|  owari version 1.11  |
|      制作・著作      |
|  ￣￣￣￣￣￣￣￣￣  |
|       Ｎ Ｈ Ｋ       |
|＿＿＿＿＿＿＿＿＿＿＿|
  ∧ ∧   ||   
(≡ω≡.)|| 
  /      づΦ   
```

![image](https://user-images.githubusercontent.com/42153744/127261436-ac34df27-1ba1-429e-8e68-e9f934b07217.png)

**Comment by xztaityozx** [comment]
う〜ん。すべてのフォント、すべてのターミナルで同じように見えるようにするのは難しいと思っています。例えば`∧`とかは報告してくださったスクショを見比べてもかなり違うと思います。

思いつきのアイデアとしては
- asciiの範囲だけに絞る
- キャラクターを持ち手の右側に寄せる
ぐらいかなと思っています。

**Comment by xztaityozx** [comment]
`∧` や`ω`を別の文字にするものありかもしれない。もうギコ猫じゃないけど

**Comment by xztaityozx** [comment]
モナーフォント基準で作って、それ以外は対応しませんとかもありかな…CLIツールなので等幅フォント基準にしたい気持ちもあるので難しい

**Comment by eggplants** [comment]
自分としては、少なくともtextimgで出力した結果が揃っていてほしいです。なのでNotoSansCJK-Regularが基準のフォントだと助かります。

**Comment by xztaityozx** [comment]
textimg側で揃うようなフォントを選ぶか、sedとかで加工すれば良いのでは？と思いました。
NotoSansCJK対応はプルリクいただけると嬉しいです。
